version: "3.3"

services:

  parser:
    build: parser-service/
    ports:
      - 8081:8081
    container_name: parser1
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    container_name: selenium1

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: postgres1
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

#  shop:
#    build: spring-shop/
#    ports:
#      - 8080:8080
#    container_name: shop1
#    links:
#      - parser
#      - postgres
#    depends_on:
#      - postgres
#      - parser